version: "3.11"

services:
  redis:
    image: redis
    restart: always

  cat:
    restart: always
    build:
      context:  ./cat
    ports:
      - "8000:8000"
    command: [ "python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]