version: "3.11"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context:  ./Cat
    ports:
      - "8000:8000"
    command: [ "python3", "./proj/manage.py", "runserver", "0.0.0.0:8000"]